apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: metrics-server
    version: 2.11.2
