apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.3.0
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            app: kube-prometheus-stack-nginx
            release: prometheus-stack
          namespace: monitoring
---
